-- CREATE TABLE IF NOT EXISTS SpotifyClone.history(
-- user_id INT NOT NULL,
-- song_id INT NOT NULL,
-- PRIMARY KEY (user_id, song_id),
-- FOREIGN KEY (user_id) REFERENCES user_info(user_id),
-- FOREIGN KEY (song_id) REFERENCES songs(song_id)
-- );

-- INSERT INTO SpotifyClone.history(user_id, song_id)
-- VALUES
-- (1, 1),
-- (1, 6),
-- (1, 14),
-- (1, 16),
-- (2, 13),
-- (2 ,17),
-- (2, 2),
-- (2, 15),
-- (3, 4),
-- (3, 6),
-- (3, 16),
-- (4, 3),
-- (4, 11),
-- (4, 18);
